server:
  port: 8085

spring:
  application:
    name: agencia-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dzmann/agencia-configuration.git
          clone-on-start: true
          default-label: main




